export enum EstadoSolicitud {
    PENDIENTE_PAGO = 'PENDIENTE_PAGO',
    PAGADA = 'PAGADA',
    RECHAZADA = 'RECHAZADA',
    VENCIDO = 'VENCIDO',
    EMITIDA = 'EMITIDA',
    PUBLICADO_VENCIDO = 'PUBLICADO_VENCIDO',
}
